export const COLLECTION_LOADING = "COLLECTION_LOADING";
export const COLLECTION_SUCCESS = "COLLECTION_SUCCESS";
export const COLLECTION_EDIT_SUCCESS ="COLLECTION_EDIT_SUCCESS";

export const EVENT_REGISTRATION_SUCCESS="EVENT_REGISTRATION_SUCCESS";
export const EVENT_REGISTRATION_FAILED="EVENT_REGISTRATION_FAILED";
export const EVENT_REGISTRATION_INIT="EVENT_REGISTRATION_INIT";
